# Generated by Django 3.1.5 on 2021-10-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='First_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Last_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='registration',
            name='branch_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='registration',
            name='contact_number1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='registration',
            name='contact_number2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gst_number',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='registration',
            name='licence_number',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='registration',
            name='pan_number',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='registration',
            name='person_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='registration',
            name='postal_code',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='registration',
            name='register_number',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='registration',
            name='state_name',
            field=models.CharField(max_length=500),
        ),
    ]
